config/routes.rb
BCA::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as=>"log_out"

  match "posts/update" => "posts#update_votes"

  match "reply/update" => "replies#update_votes"

  match "post/search" => "posts#search"

  match "user/search" => "users#search"

  match "posts/destroy" => "posts#destroy"

  match "replies/destroy" => "replies#destroy"

  match "users/destroy" => "users#destroy"
  
  match "posts/admin_index" => "posts#admin_index"

  match "users/grant_admin" => "users#grant_admin"

  match "users/revoke_admin" => "users#revoke_admin"

  match "admin/post_activity" => "admin#post_activity"

  resources :admin

  resources :sessions

  resources :replies

  resources :posts

  resources :users

  root :to=> "users#new"

end

app/models/reply.rb
#
# This model is used to store replies created by user.
# It contains following fields
#    1. reply
#    2. User_id of the user who created the post.
#
class Reply < ActiveRecord::Base
  #
  # Each reply is associated with a post.
  #
  belongs_to :post

  #
  # This is used for creating votes
  # table(replies_users) which is join of both users and replies table.
  #
  #
  belongs_to :replies_users
  has_and_belongs_to_many :users
  #
  # Performing validations on each field.
  #
  validates_presence_of :reply
  validates_presence_of :post_id
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  # GET /replies
  # GET /replies.json

  # This action list all the replies along with its posts.
  def index
    @replies = Reply.all
    @votes = Hash.new
    @notice = params[:notice]

    for reply in @replies
      @votes[reply.id] = RepliesUsers.get_vote_count(reply.id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  # lists all the replies for given post.
  def new
    @reply = Reply.new
    @reply.post_id = params[:post_id]
    @replies = Reply.find_all_by_post_id(@reply.post_id)

    respond_to do |format|
      format.html  # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
  end

  # POST /replies
  # POST /replies.json
  def create
    authorize
    @reply = Reply.new(params[:reply])
    @reply.user_id = current_user.id

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render json: @reply, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @reply = Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :ok }
    end
  end

  def update_votes
    @user = current_user
    @reply_id = params[:reply_id]

    msg = RepliesUsers.vote(@user.id, @reply_id)

    redirect_to :action => "index", :notice => msg

  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= stylesheet_link_tag 'replies_form', :media => 'screen' %>
<%= stylesheet_link_tag 'cssreplies', :media => 'screen' %>
<%= form_for(@reply) do |f| %>
    <% if @reply.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

          <ul>
            <% @reply.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field" style="width: 90%" >
      <h3><%= f.label :Post %><br/></h3>
      <%= f.hidden_field :post_id, :value=> @reply.post_id %>
      <strong> Title:</strong> <%= f.label Post.find(@reply.post_id).title %>
      <br/>
      <strong>Message:</strong> <%= f.label Post.find(@reply.post_id).message %>
      <br/>
    </div>
    <table  bgcolor="white" style="background-color: #ffffff; border: #ffffff" width="90%">
      <h3>Replies</h3>
      <tr>
        <td>
          <h3>User</h3>
        </td>
        <td></td>
        <td></td>
        <td>
          <h3>Reply</h3>
        </td>
      </tr>
        <% for rep in @replies %>
           <tr style="background-color: #ffffff;">
             <td><%= User.find(rep.user_id).username %></td>
             <td></td>
             <td></td>
        <td><%= rep.reply %></td>
        </tr>
           <% end %>
    </table>

    <br>
    <div class="field">
      <h3><%= f.label :reply %></h3>
      <br/>
      <%= f.text_area :reply %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/replies/edit.html.erb
<h2>Editing reply</h2>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
 <%= javascript_include_tag :all %>
 <%=@notice %>
<h2>Listing replies</h2>

<table>
  <tr>
    <th>Reply</th>
    <th>Post title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @replies.each do |reply| %>
  <tr>
    <td><%= reply.reply %></td>
    <td><%= Post.find(reply.post_id).title%></td>
    <td><%= link_to "Vote(#{@votes[reply.id]})", :method => :post, :controller => :replies, :action => :update_votes, :reply_id => reply.id %></td>
    <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
    <td><%= link_to 'Destroy', :id=>reply.id, :action=>:destroy, :controller => :replies %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Posts', :controller => :posts, :action=> :index%>

app/views/replies/new.html.erb
<table bgcolor="#FFF8DC" style="position: absolute; top:100px; right:10px; background-color: #FFF8DC">
  <td align="right">
    <p align="right">
      <%= link_to 'Posts', :back %>
      <%= link_to 'New Post', new_post_path %>
      <%= link_to_if @curr_user, "Logout", :log_out %>
    </p>
  </td>
</table>
<%= render 'form' %>

app/views/replies/show.html.erb
<p id="notice"></p>

<p>
  <b>Reply:</b>
  <%= @reply.reply %>
</p>

<p>
  <b>User:</b>
  <%= User.find(@reply.user_id).username %>
</p>

<p>
  <b>Post:</b>
  <%= Post.find(@reply.post_id).title %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Posts', :action => :index, :controller => :posts %>