config/routes.rb
BCA::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as=>"log_out"

  match "posts/update" => "posts#update_votes"

  match "reply/update" => "replies#update_votes"

  match "post/search" => "posts#search"

  match "user/search" => "users#search"

  match "posts/destroy" => "posts#destroy"

  match "replies/destroy" => "replies#destroy"

  match "users/destroy" => "users#destroy"
  
  match "posts/admin_index" => "posts#admin_index"

  match "users/grant_admin" => "users#grant_admin"

  match "users/revoke_admin" => "users#revoke_admin"

  match "admin/post_activity" => "admin#post_activity"

  resources :admin

  resources :sessions

  resources :replies

  resources :posts

  resources :users

  root :to=> "users#new"

end

app/models/user.rb
#
# This model is used to store user information. Every registered user has entry in Users table.
# It performs hashing before storing the password and it provides methods to authenticate, encrypt and generate_salt methods.
#

class User < ActiveRecord::Base
  # A user can have many posts and replies.

  has_one :session
  has_many :posts, :dependent=>:destroy
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :replies


  #Email validation regular expression 
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Creating a virtual attribute fetching clear_text_password from the user.
  attr_accessor :clear_text_password;

  # Performing basic validations including password field length which should be atleast six characters in length.
  validates_presence_of :username
  validates_uniqueness_of :username
  validates :clear_text_password, :presence => true, :length => {:minimum => 6}
  validates_confirmation_of :clear_text_password

  validates_presence_of :e_mail
  validates_uniqueness_of :e_mail
  validates :e_mail, :presence => true,
            :format => {:with => email_regex}


  # This method is used to authenticate a user while login.
  def User.authenticate(name, password)
    # It first checks if user is already registered and then encrypts given password and checks it with encrypted value in database.
    if user = find_by_username(name)
      if user.password == encrypt_password(password)
        user
      end
    end
  end

  # Virtual attribute
  def clear_text_password=(password)
    @clear_text_password = password
    if password.present?
      generate_salt
      self.password = self.class.encrypt_password(password)
    end
  end

  # This method encrypts the given password using SHA2 digest algorithm.
  def User.encrypt_password(password)
    if password.present?
      Digest::SHA2.hexdigest(password)
    end
  end

  private
  # This method generates salt and can be used if more stronger security is required. If used then it uses HMAC algorithm with generated salt as the key.
  def generate_salt
    @salt = self.object_id.to_s + rand.to_s
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  skip_before_filter :authorize, :only => [:new, :create, :show, :index, :search]

  # This method uses
  def index
    @users = User.all
    @isDeletable = Array.new
    for user in @users
          @isAdmin = current_user.admin_rights
          @isDeletable[user.id] = (user.id == current_user.id) || current_user.admin_rights
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
     @isAdmin = current_user.admin_rights
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        flash[:notice] = "User #{@user.username} successfully created!"
        format.html { redirect_to @user }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = "User #{@user.username} successfully updated!"
        format.html { redirect_to @user }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    posts = Post.find_all_by_user_id(@user.id)

    for post in posts
      post.destroy
    end

    @user.destroy

    flash[:notice] = "User has been successfully deleted"
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

    def search

    @user_opt = params[:q]
    @users = User.where("username like ?", @user_opt +"%")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

def revoke_admin
      @user = User.find(params[:id])
      #check if the user has admin rights , if yes revoke admin rights
    if @user.admin_rights
      #check if the current user is the same as the user whose admin rights are being revoked.
      #If yes, prohibit the user from revoking admin rights
      if @user.username != current_user.username
        @user.admin_rights = nil
        #save the changes made to the admin_rights column of the user table
        if @user.save(:validate => false)
            flash[:notice] = "Admin rights have been revoked for #{@user.username}   "
        else
              flash[:notice] = "Error revoking admin rights"
        end
      else
        flash[:notice] = "Permission denied! You cannot revoke Admin rights from self"
        end
      else
      flash[:notice] = " #{@user.username} is not an admin  "
    end

 # format.html { redirect_to :controller=>:admin, :action=>:index }
  redirect_to :controller=>:admin, :action=>:index
  end

def grant_admin
    #Grant admin privileges to a user
    # Get the user
    @user = User.find(params[:id])
    #Check if the user is already an admin, If no, grant admin rights.
    if !@user.admin_rights
    @user.admin_rights= 'true'
   if @user.save(:validate => false)
    flash[:notice] = "#{@user.username} has been granted admin privileges"
  else
    flash[:notice] = "Error when granting admin privileges"
  end
    else
      flash[:notice] = "#{@user.username} is already an admin"
    end
  #format.html { redirect_to :controller=>:admin, :action=>index }
    redirect_to :controller=>:admin, :action=>:index
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :username %>
      <br/>
      <%= f.text_field :username %>
    </div>
    <br/>
    <div class="field">
      <%= f.label :password %>
      <br/>
      <%= f.password_field :clear_text_password %>
    </div>
    <br/>
    <div class="field">
      <%= f.label :password_confirmation %>
      <br/>
      <%= f.password_field :clear_text_password_confirmation %>
    </div>
    <br/>
    <div class="field">
      <%= f.label :e_mail %>
      <br/>
      <%= f.text_field :e_mail %>
    </div>
    <br/>
    <!--<div class="field">
    <%= f.label :admin_rights %>
    <%= f.text_field :admin_rights %>
  </div>-->

    <div class="actions">
        <%= f.submit %>
    </div>
    <br/>
<% end %>
<div>

</div>

app/views/users/edit.html.erb
<h2>Editing user</h2>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2 align ="center">Listing users</h2>

   <table bgcolor="#FFF8DC" style="position: absolute; top:100px; right:10px; background-color: #FFF8DC">
      <td align="right">
<p align="right">
  <%= link_to 'Back', :back  %>
  <%= link_to_if @isAdmin, 'New User', new_admin_path %>
  <%= link_to 'New Post', new_post_path %>
  <%= link_to_if @curr_user, "Logout", :log_out%>
  <%= form_tag({:controller=>:posts ,:action =>:search}, :method => "get") do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= select_tag(:user_opt, options_for_select( [['posts', 1], ['users', 2]])) %>
      <%= submit_tag("Search") %>
  <% end %>
</p>
          </td>
   </table>

<table align="center">
  <tr>
    <th colspan="10" style="background-color:#b0e0e6;">Username</th>
    <th colspan="15" style="background-color:#b0e0e6;">Email</th>
    <th colspan="5" style="background-color:#b0e0e6;">Show</th>
    <th colspan="5" style="background-color:#b0e0e6;">Edit</th>
    <th colspan="5" style="background-color:#b0e0e6;">Destroy</th>
    <th colspan="5" style="background-color:#b0e0e6;">Grant Admin</th>
    <th colspan="5" style="background-color:#b0e0e6;">Revoke Admin</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td colspan="10"><%= user.username %></td>
    <td colspan="15"><%= user.e_mail %></td>
    <td colspan="5"><%= link_to 'Show', user %></td>
    <td colspan="5"><%= link_to_if @isDeletable[user.id], 'Edit', edit_user_path(user) %></td>
    <td colspan="5"><%= link_to_if @isDeletable[user.id], 'Destroy', :id=>user.id, :action=>:destroy, :controller => :users %></td>
    <td colspan="5"><%= link_to_if @isAdmin, 'Grant Admin', :action => :grant_admin, :id=> user.id %></td>
    <td colspan="5"><%= link_to_if @isAdmin, 'Revoke Admin', :action => :revoke_admin, :id=> user.id%></td>
  </tr>
      <tr>
    <td colspan="10" style="background-color:#b0e0e6;"></td>
    <td colspan="15" style="background-color:#b0e0e6;"></td>
    <td colspan="5" style="background-color:#b0e0e6;"></td>
    <td colspan="5" style="background-color:#b0e0e6;"></td>
    <td colspan="5" style="background-color:#b0e0e6;"></td>
    <td colspan="5" style="background-color:#b0e0e6;"></td>
    <td colspan="5" style="background-color:#b0e0e6;"></td>
      </tr>
<% end %>
</table>
</div>

<br />

app/views/users/new.html.erb
<table>

<tr valign="top">
  <td style="background-color:#FFF8DC;width:800px;text-align:top;">
<h2 align="center">New User? Register</h2>

<%= render 'form' %>
<div style="float:left;">
  <%= button_to "Login", new_session_path, :method => :get %>
</div>

<td style="background-color:#FFF8DC;height:600px;width:800px;text-align:top;">
  <div>


        <div align=center>
          <h2 align="center">Search</h2>
          <%= form_tag({:controller=>:posts ,:action =>:search}, :method => "get") do %>
              <%= label_tag(:q, "Search for:") %>
              <%= text_field_tag(:q) %>
              <%= select_tag(:user_opt, options_for_select( [['posts', 1], ['users', 2]])) %>
              <%= submit_tag("Search") %>
          <% end %>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/users/search.html.erb
<%= stylesheet_link_tag 'posts', :media => 'screen' %>
<h2 align="center">Search results for : <i><%= @user_opt%></i> </h2>

<table>
  <tr>
    <th>Username</th>
    <th>E-mail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.e_mail %></td>
    <td><%= link_to 'Show', user %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice">
  <!--<%= notice %>-->
</p>

<p>
  <!-- show the username -->
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <!-- show the email -->
  <b>E-mail:</b>
  <%= @user.e_mail %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'login', new_session_path %> |
<%= link_to_if @isAdmin, 'Admin Control', :controller => :admin, :action => :index  %>