config/routes.rb
BCA::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"

  get "log_out" => "sessions#destroy", :as=>"log_out"

  match "posts/update" => "posts#update_votes"

  match "reply/update" => "replies#update_votes"

  match "post/search" => "posts#search"

  match "user/search" => "users#search"

  match "posts/destroy" => "posts#destroy"

  match "replies/destroy" => "replies#destroy"

  match "users/destroy" => "users#destroy"
  
  match "posts/admin_index" => "posts#admin_index"

  match "users/grant_admin" => "users#grant_admin"

  match "users/revoke_admin" => "users#revoke_admin"

  match "admin/post_activity" => "admin#post_activity"

  resources :admin

  resources :sessions

  resources :replies

  resources :posts

  resources :users

  root :to=> "users#new"

end

app/models/post.rb
#
# This model is used to store posts created by user.
# It contains following fields
#    1. Title
#    2. Message
#    3. User_id of the user who created the post.
#
class Post < ActiveRecord::Base
  #
  # Each post can have many replies and when a post is deleted
  # then all of its associated replies can also be deleted.
  #
  has_many :replies, :dependent=>:destroy
  #
  # THis is used for creating votes
  # table(posts_users) which is join of both users and posts table.
  #
  #
  has_and_belongs_to_many :users

  #
  # Performing validations on each field.
  #
  validates_presence_of :title
  validates_presence_of :message
  validates_presence_of :user_id
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts
  # GET /posts.json
  skip_before_filter :authorize, :only => [:show, :index, :search]



  # This action is used display all the posts in order defined by a metric. This metric is dependent on vote_cont and creation date.
  def index
    @posts = Post.all
    @votes = Hash.new
    @isDeletable = Array.new
    @isAdmin = current_user.admin_rights
    @notice = params[:notice]
    @user = current_user
    @post_metric_map= Hash.new
    ## create a votes variable and initialize it with vote count and display them index page


    for post in @posts
    @isDeletable[post.id] = (post.user_id == @user.id) || @user.admin_rights
    #here we write our metric by which the posts are sorted.
       @alpha=0.5     # this (0<alpha<1) value determines the importance we give to vote count and created time
                      # e.g. To give high importance to vote count, keep the alpha value low.
       @beta=86400    # this value is used to scale the 'time since creation' . We consider here that
                      # the messages that has been created in one day to be in the same level.
       @votes[post.id] = PostsUsers.get_vote_count(post.id)
       metric = (1-@alpha)*post.vote_count + @alpha*(post.created_at.to_time.to_i() - Time.now().to_i)/@beta
       post.metric=metric
      post.save
    end

    @posts = Post.find(:all, :order => 'metric' ).reverse
   # @post_metric_map.sort_by {|id, metric| metric}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end


  # GET /posts/new
  # GET /posts/new.json
  def new
    authorize
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    authorize
    @post = Post.find(params[:id])
    @user = current_user
    @post_user_id = @post.user_id
  end

  # POST /posts
  # POST /posts.json
  def create
    authorize
    @user = current_user
    @post = Post.new(params[:post])
    @post.user_id = @user.id

    respond_to do |format|
      if @post.save
        flash[:notice] =  'Post was successfully created.'
        format.html { redirect_to @post}
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    authorize
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize            # before destroying any user it has to be authorized.
    @post = Post.find(params[:id])
    @user = current_user

    @post.destroy
         respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
      end
  end

  #
  # Updates votes when ever a user casts votes.
  #
  def update_votes
    @user = current_user
    @post_id = params[:post_id]
    post=Post.find(@post_id)

    post.save

    msg = PostsUsers.vote(@user.id, @post_id)

    redirect_to :action => "index", :notice => msg

  end

  #
  #
  # This action searches for all the posts either posted by given user or by post title.
  #
  def search
     @user_opt = params[:user_opt]
     @key = params[:q]
     @votes = Hash.new
     @msg = ""
     @isDeletable = Array.new
     @posts = Array.new
     @user = current_user

     if @user_opt.to_i == 1
       @posts = Post.where("title like ? or message like ?", "%" + params[:q] +"%","%"+ params[:q] + "%")
       ## create a votes variable and initialize it with vote count and display them index page
     else
       @users = User.where("username like ?", "%" + params[:q] +"%")
       for user in @users
           @posts = @posts + Post.find_all_by_user_id(user.id)
         end
     end

     for post in @posts
             @votes[post.id] = PostsUsers.get_vote_count(post.id)
     end

     # Checking which of the posts user can delete
     for post in @posts
       @isDeletable[post.id] = (post.user_id == @user.id) || @user.admin_rights
     end

     if @posts.empty?
         @msg = "No search results found. Try new search"
     end
     respond_to do |format|
         format.html # show.html.erb
         format.json { render json: @post }
     end

   end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field" >
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editing post</h2>

<%= render 'form' %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts', :media => 'screen' %>
<%= @notice %>

 <div align="center">
   <table bgcolor="#FFF8DC" style="position: absolute; top:100px; right:10px; background-color: #FFF8DC">
      <td align="right">
<p align="right">
  <%= link_to 'Back', :back  %>   |
  <%= link_to 'New Post', new_post_path %>  |
  <%= link_to_if @curr_user, "Logout", :log_out%>   |
  <%= form_tag({:controller=>:posts ,:action =>:search}, :method => "get") do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= select_tag(:user_opt, options_for_select( [['posts', 1], ['users', 2]])) %>
      <%= submit_tag("Search") %>
  <% end %>
</p>
          </td>
   </table>
  <br/>
   <br/>
   <br/>
<h2 align ="center">Listing posts</h2>
<table>
  <tr>
    <th colspan="5" style="background-color:#b0e0e6;"><h2>Title</h2></th>
    <th colspan="10" style="background-color:#b0e0e6;"><h2>Message</h2></th>
    <th colspan="2" style="background-color:#b0e0e6;"><h2>User</h2></th>
    <th colspan="2" style="background-color:#b0e0e6;"><h2>Vote</h2></th>
    <th colspan="2" style="background-color:#b0e0e6;"><h2>Reply</h2></th>
    <th colspan="2" style="background-color:#b0e0e6;"><h2>Edit</h2></th>
    <th colspan="2" style="background-color:#b0e0e6;"><h2>Delete</h2></th>
  </tr>


      </td>
</tr>

<% @posts.each do |post| %>
  <tr>
    <td colspan ="5">
      <%= post.title %>
    </td>
    <td colspan="10">
      <%= post.message %>
    </td>
    <td colspan="2">
      <%= User.find(post.user_id).username%>
    </td>

    <td colspan="2">
    <%=link_to "Vote(#{@votes[post.id]})", :method => :post, :controller => :posts, :action => :update_votes, :post_id => post.id %>
    </td>
   <td colspan="2">
   <%= link_to 'Reply', new_reply_path(:post_id=>post.id)%>
   </td>
    <td colspan="2">
      <%= link_to_if @isDeletable[post.id], 'Edit', edit_post_path(post) %>
    </td>
   <td colspan="2">
   <%= link_to_if @isDeletable[post.id], 'Destroy', :id=>post.id,:action=>:destroy, :controller => :posts %></td>
  </tr>
   <td colspan="5" style="background-color:#b0e0e6;">
   </td>
    <td  colspan="10" style="background-color:#b0e0e6;">
   </td>
   <td  colspan="2" style="background-color:#b0e0e6;">
   </td>
    <td colspan="2" style="background-color:#b0e0e6;">
   </td>
    <td  colspan="2" style="background-color:#b0e0e6;">
   </td>
      <td  colspan="2" style="background-color:#b0e0e6;">
   </td>
      <td  colspan="2" style="background-color:#b0e0e6;">
   </td>

<% end %>
</table>

</div>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<%= stylesheet_link_tag 'posts', :media => 'screen' %>
<h2 align="center">Search results for : <i><%= @key%></i> </h2>

   <table bgcolor="#FFF8DC" style="position: absolute; top:100px; right:10px; background-color: #FFF8DC">
      <td align="right">
<p align="right">
  <%= link_to_if @isAdmin, 'Admin Control', :controller => :admin, :action => :index  %>   |
  <%= link_to 'Back', :back  %> |
  <%= link_to 'New Post', new_post_path %>  |
  <%= link_to_if @curr_user, "Logout", :log_out%>  |
  <%= form_tag({:controller=>:posts ,:action =>:search}, :method => "get") do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= select_tag(:user_opt, options_for_select( [['posts', 1], ['users', 2]])) %>
      <%= submit_tag("Search") %>
  <% end %>
</p>
          </td>
   </table>

<table>
  <tr>
    <th colspan="1">Title</th>
    <th colspan="1">Message</th>
    <th colspan="1">User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


      </td>
</tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.message %></td>
    <td><%= User.find(post.user_id).username%></td>
    <td><%= link_to "Vote(#{@votes[post.id]})", :method => :post, :controller => :posts, :action => :update_votes, :post_id => post.id %></td>
    <td><%= link_to 'Reply', new_reply_path(:post_id=>post.id)%></td>
    <td><%= link_to_if @isDeletable[post.id], 'Edit', edit_post_path(post) %></td>
    <td><%= link_to_if @isDeletable[post.id], 'Destroy', :id=>post.id,:action=>:destroy, :controller => :posts %></td>

      </tr>
   <td colspan="2" style="background-color:#98F5FF;">
     </td>
<% end %>
</table>


<%= @msg%>
<%= link_to 'New Search', :back %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Message:</b>
  <%= @post.message %>
</p>

<p>
  <b>User:</b>
  <%= User.find(@post.user_id).username %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Posts', :action => :index %>
<%= link_to 'Reply',  new_reply_path(:post_id=>@post.id, :post_title=>@post.title, :post_message=>@post.message)%>